### ISSUE TITLE
bug: slow cursor when used with tagbar

### ISSUE THREAD

**Issue by Kaesenudeln** [freddiehaddad/feline.nvim#105]
### Did you check docs and existing issues?

- [X] I have read all the Feline docs
- [X] I have searched the existing issues of Feline
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.1.1

### Describe the bug

When feline and preservim/tagbar used together, opening large files will cause the cursor to move extremely slow.

### Steps To Reproduce

1. Open tagbar with multiple tags in a large file
2. Move the cursor

### Expected Behavior

Cursor movement will not be smooth when tagbar not in use or feline uninstalled.

**Comment by freddiehaddad** [comment]
Hello, thanks for the bug report. What makes you think the issue is with feline?

1. Does the slow cursor issue stop if you disable feline?
2. Do you have any custom components configured? If so, did you try disabling them?

**Comment by Kaesenudeln** [comment]
1. Yes. The cursor movement will be smooth after disabling feline. And FYI, airline users have reported similar issues

**Comment by freddiehaddad** [comment]
Thank you for the extra details!

What's your update time set to? The default is `4000ms`.

```
:set updatetime?
```

Can you try setting it to 250ms if the value is greater and see if that improves anything?

```
:set updatetime=250
```

**Comment by Kaesenudeln** [comment]
> Thank you for the extra details!
> 
> What's your update time set to? The default is `4000ms`.
> 
> ```
> :set updatetime?
> ```
> 
> Can you try setting it to 250ms if the value is greater and see if that improves anything?
> 
> ```
> :set updatetime=250
> ```

My `updatetime` is set to 50. I have tried lower and higher values. Didn't help.

**Comment by freddiehaddad** [comment]
Does the tagbar window have a filetype? If it does, can you try adding that filetype to the inactive list for feline in your config?

```lua
force_inactive.buftypes = {
    'terminal',
    'NEO-TREE',
    'neo-tree'
}
```

**Comment by freddiehaddad** [comment]
If you look at your configuration, you have active and inactive configurations. The active configuration is shown when the buffer has the focus, and the inactive configuration is shown for buffers that do not have the focus.

If you added the tagbar window's filetype to `force_inactive.filetypes` (btw, you can lookup the filetype by moving the cursor to that pane and typing `set ft?`), and that didn't work. Try reducing the number of inactive components. Maybe to start, just show the filename and slowly add one component at a time until the problem returns.  This way we can try to see exactly what's causing it.

**Comment by freddiehaddad** [comment]
FWIW, `ctags` is somewhat of a legacy vim feature. Have you considered using treesitter and a lua plugin to display class definitions, methods, etc.?

**Comment by Kaesenudeln** [comment]
> FWIW, `ctags` is somewhat of a legacy vim feature. Have you considered using a language server, treesitter and a lua plugin to display class definitions, methods, etc.?
> 
> Something like https://github.com/stevearc/aerial.nvim for viewing a list of class properties.

I didn't realize that actually. I tried the solutions provided above but no luck. Considering your valuable suggestion, I replaced tagbar with a LSP powered plugin and that has eliminated the "slow cursor" problem. Thank you very much for your kind help!
