### ISSUE TITLE
feature: statuscolumn support?

### ISSUE THREAD

**Issue by mrjones2014** [freddiehaddad/feline.nvim#17]
### Did you check the docs?

- [X] I have read all the Feline docs

### Is your feature request related to a problem? Please describe.

Would like to be able to configure statuscolumn with feline.nvim, just like heirline.nvim can.

### Describe the solution you'd like

Same sort of API as statusline and winbar, but for statuscolumn

### Describe alternatives you've considered

doing it manually, or spending dozens of hours switching to heirline, which I'm hesitant to do because it doesn't help with highlights as much as feline does

### Additional context

I started some work on it in my fork here but can't get it to work, but I think I'm probably just missing some feline.nvim context. I don't think it should be too much work to support it. https://github.com/mrjones2014/feline.nvim

**Comment by freddiehaddad** [comment]
I'll look at your fork this weekend and follow up.  Sounds like a good idea.

**Comment by freddiehaddad** [comment]
Looking at your fork, I'm wondering if the lua script being part of the string is the issue:

`vim.o.statuscolumn = "%{%v:lua.require'feline'.generate_statuscolumn()%}"`

The vim help docs suggest that the string will not execute lua code.  I think formatting the string and then setting the the value is what we need to do.  Admittedly, I could be wrong about this.  I'm educating myself on configuring the statuscolumn still.

**Comment by freddiehaddad** [comment]
Looking at heirline, maybe I'm wrong.  I'll experiment more with this.

**Comment by freddiehaddad** [comment]
Left some comments in your code.  Still educating myself on the statuscolumn stuff in the docs.

**Comment by freddiehaddad** [comment]
I have an initial implementation working.  You were very close, just a couple typos in the code and no default values provided.  We can work from your fork or continue development in the `statuscolumn` branch I created.

**Comment by freddiehaddad** [comment]
I think the next step is setting defaults that make sense and probably mimic the default neovim setup.

**Comment by freddiehaddad** [comment]
I added an example provider showing the status column being updated with the line number of the cursor.  This covers end-to-end solution.  Note, this is NOT the correct way to populate the line number.  The provider is an example of something custom.  The line number can be provided via the proper statuscolumn variable.

**Comment by freddiehaddad** [comment]
@mrjones2014 would you mind testing out the sign column and reviewing the PR?

https://github.com/freddiehaddad/feline.nvim/pull/18

**Comment by mrjones2014** [comment]
Tested locally, all seems to work 👍

**Comment by freddiehaddad** [comment]
Thanks for helping validate! I pushed up some documentation updates this morning and will merge shortly.  Happy we built this feature together and appreciate the suggestion.
