### ISSUE TITLE
bug: Lazy.nvim installs the `master` branch, not the `main` branch 

### ISSUE THREAD

**Issue by primeapple** [freddiehaddad/feline.nvim#25]
### Did you check docs and existing issues?

- [X] I have read all the Feline docs
- [X] I have searched the existing issues of Feline
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0

### Operating system/version

Arch

### Describe the bug

When I use `lazy.nvim` to install your plugin with the config

```
    {
        'freddiehaddad/feline.nvim',
        lazy = false,
    }
```
It actually installs the wrong version:
`  "feline.nvim": { "branch": "master", "commit": "c6eea890c4f81725f4c51eba48d9733a248513a2" },`
( from `lazy-lock.json` )

This might be a lazy problem, but maybe you have some git setting pointing to `master` as the default branch?

## Workaround
Add `branch = 'main'` and now it works.

### Steps To Reproduce

See description

### Expected Behavior

Install latest version

### Repro

```Lua
require("lazy").setup({
  {
    "freddiehaddad/feline.nvim",
    config = function()
      -- your configuration
    end,
  }
})
```

**Comment by freddiehaddad** [comment]
The branch was changed from master to main a while back.  I wonder if your lock file hard-coded a branch the first time it synced back when the branch was master? It looks like you resolved the problem by explicitly using branch main, the other I presume would be to remove the plugin and install it again. For the latter, you don't need to delete your config.
