### ISSUE TITLE
bug: LuaRocks GHA failing on dependency.

### ISSUE THREAD

**Issue by freddiehaddad** [freddiehaddad/feline.nvim#73]
### Did you check docs and existing issues?

- [X] I have read all the Feline docs
- [X] I have searched the existing issues of Feline
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

na

### Operating system/version

na

### Describe the bug

@mrcjkb  github action is failing with:

```text
Error: Failed installing dependency: https://luarocks.org/gitsigns.nvim-scm-1.rockspec - Build error: Failed installing lua/gitsigns/diff_ffi.lua in /home/runner/work/_temp/tmp.n5kdcAxHNW/lib/luarocks/rocks-5.1/gitsigns.nvim/scm-1/lua/gitsigns/diff_ffi.lua: lua/gitsigns/diff_ffi.lua: No such file or directory
```
https://github.com/freddiehaddad/feline.nvim/actions/runs/8754394451/job/24026039795#step:4:485

Looking into the problem, but maybe you can shed some light. I do see gitsigns registered with LuaRocks, so I don't think the issue is there.

### Steps To Reproduce

Run the GHA workflow.

### Expected Behavior

Successful push to LuaRocks repository.

### Repro

```Lua
na
```

**Comment by freddiehaddad** [comment]
@mrcjkb The person got tagged in the above bug report. Tagging again here in case the update didn't send you a notification.

**Comment by mrcjkb** [comment]
Yep, gitsigns.nvim doesn't have a non-scm release yet (they're working on it).
I would recommend waiting till it's been resolved (see https://github.com/lewis6991/gitsigns.nvim/pull/964#issuecomment-2061185572).

**Comment by mrcjkb** [comment]
The rockspec isn't strictly necessary (luarocks-tag-release generates one based on GitHub repo metadata and the inputs), but it's still useful if you want to publish an scm/dev version.
