### ISSUE TITLE
Bring back `feline.add_theme()`

### ISSUE THREAD

**Issue by mawkler** [freddiehaddad/feline.nvim#8]
[This PR](https://github.com/famiu/feline.nvim/pull/267/files#diff-1b3126d2bffd4e76709977800a5ecd86596da9d600a2f8a4184ddf4e8bd83f58L103-L105) seems to remove `feline.add_theme()`. It doesn't mention why, and `add_theme()` is still in [the helpdocs](https://github.com/freddiehaddad/feline.nvim/blob/main/doc/feline.txt#L1088) which makes me belive that it was removed by mistake by @famiu.

**Comment by freddiehaddad** [comment]
I'm not sure of the history behind removing `add_theme` I'll look info that.  In the meantime, `use_theme` exists and works.  Will that help wit your particular issue?

Example:

```lua
local theme = {
	black = "",
	skyblue = "",
	cyan = "",
	green = "",
	oceanblue = "",
	magenta = "",
	orange = "",
	red = "",
	violet = "",
	white = "",
	yellow = "",
}
require("feline").use_theme(theme)
```

**Comment by freddiehaddad** [comment]
Looking at the PR, I think you're right.  I created a new PR #9 which adds it back, but I'm going to make sure nothing breaks before merging it.
